baseurl = "https://hiratasaori.com/"
languageCode = "en-us"
title = "Hirata Saori | 平田 小織"
theme = "hugo-strata-theme"


# hugo-strata-theme のソース
disqusShortname = "hirata-saori"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-93372029-1"
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "平田 小織"
	description = ""

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = [ "/js/prism.js" ]
	custom_css  = [ "/css/prism.css", "/css/custom.css" ]


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio_jp = "平田 小織"
		bio_en = "Hirata Saori"
		# The icons will be shown if you enter your username
		github = "hiratasaori"
		facebook = "saori.hirata.167"
    twitter = "saori_hirata"
		# googleplus = "109378861229646006280"
		# gitlab = "spf13"
		# dribbble = ""
		# flickr = ""
		# linkedin = ""

		copyright = [
			# "&copy; John Doe"
		]


	[params.about]
		hide  = false
		title = "Profile"
		content = "兵庫県生まれです。<br />大阪のデザイン制作会社で Web デザインやマークアップをさせていただいてます。<br />好きな食べ物は納豆とラーメンで、休みの日は映画を観たり、近所をサイクリングしたりしてます。<br />関西圏で美味しいラーメン屋さんがあったらぜひ教えてください＾＾"


	[params.portfolio]
		hide  = true
		title = "Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "タイトルが入ります"
			description = "こちらに説明文が入ります"

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "タイトルが入ります"
			description = "こちらに説明文が入ります"

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "タイトルが入ります"
			description = "こちらに説明文が入ります"

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "タイトルが入ります"
			description = "こちらに説明文が入ります"

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "タイトルが入ります"
			description = "こちらに説明文が入ります"

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "タイトルが入ります"
			description = "こちらに説明文が入ります"

	[params.recentposts]
		hide  = false
		title = "Note"

	[params.contact]
		hide  = true
		title = "Get In Touch"
		content = "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."

		address = [
			"1234 Somewhere Rd.",
			"Nashville, TN 00000",
			"United States"
		]
		phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "hello@example.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "Note"
	url  = "post/"
	weight = 10
